# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build Backend
      run: dotnet build --no-restore
      
    - name: Restore Frontend
      working-directory: 'Pulsar/WebApp'
      run: npm ci 
      
    - name: Build Frontend
      working-directory: 'Pulsar/WebApp'
      run: npm run build
